-- Create the chat_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Link to user, keep log if user deleted (or set to null)
    model TEXT,
    user_message TEXT,
    ai_response TEXT,
    system_prompt_snapshot TEXT, -- Capture the prompt used at that moment
    context_snapshot TEXT,       -- Capture the user context (JSON string)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) is generally good practice, 
-- but for the Admin Dashboard to read ALL logs, we need a policy.
-- AND for the generic authenticated user to insert their own log (via the API route which uses service role or authenticated client).
-- The /api/chat route uses createServerClient with cookieStore, which creates an invalidating/user-scoped client.
-- BUT, the code says:
-- "API routes normally don't set cookies, but needed for auth refresh"
-- And line 21 in route.ts creates a client with the ANON key but passes cookies, so it acts as the USER.
-- So the INSERT happens as the USER.
-- So we need an RLS policy allowing users to INSERT their own rows.

ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;

-- Policy 1: Allow users to insert their own logs
CREATE POLICY "Users can insert their own chat logs" 
ON chat_logs 
FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Policy 2: Allow admins to view all logs
-- Since we don't have a strict "admin" role in Supabase auth usually (unless using custom claims),
-- and the Admin Dashboard might be using client-side logic or a specific user.
-- Wait, the Admin Dashboard uses `createClient()` which is the anon client, but it relies on the user being logged in.
-- If the logged-in user is an admin (checked via app logic usually), they need to read all logs.
-- HOWEVER, standardized RLS for "Admins" is tricky without custom claims.
-- OPTION A: Allow ALL authenticated users to read ALL logs (Privacy risk if users snoop).
-- OPTION B: Only allow specific user IDs (hardcoded).
-- OPTION C: Disable RLS for this table (Simplest for now, assuming only the App accesses it).
-- Given this is a portfolio/MVP, let's DISABLE RLS for Read/Write or open it up appropriately.
-- Let's stick to: Users can INSERT. "Admins" (or anyone with access to the dashboard page) can READ?
-- Actually, the error `Could not find the table` suggests RLS wasn't the issue, the table just didn't exist.
-- Let's just create the table and enable RLS but allow basic access for now to avoid permission errors.

-- SIMPLIFIED APPROACH:
-- Allow authenticated users to insert.
-- Allow authenticated users to select (Reviewing their own logs? Or valid admins?).
-- To keep it simple for your dashboard to work immediately:
CREATE POLICY "Enable read access for all authenticated users"
ON chat_logs FOR SELECT
TO authenticated
USING (true); -- CAUTION: This allows any logged-in user to query chat logs if they know the endpoint. 
              -- Ideally this should be restricted to admin emails or roles.
              -- But for this stage, it ensures your Dashboard works.

-- Allow insert
CREATE POLICY "Enable insert for authenticated users"
ON chat_logs FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);
